CREATE DATABASE [MIKITA_KURAPATAU_DB];
GO
USE [MIKITA_KURAPATAU_DB];
GO
CREATE SCHEMA sales;
GO
CREATE SCHEMA persons;
GO
CREATE TABLE sales.Orders (OrderNum INT NULL);

BACKUP DATABASE [MIKITA_KURAPATAU_DB] TO DISK = 'C:\dbs\lab1\Nikita_Kuropatov.bak';
GO
DROP DATABASE [MIKITA_KURAPATAU_DB];
GO
RESTORE DATABASE [MIKITA_KURAPATAU_DB] FROM DISK = 'C:\dbs\lab1\Nikita_Kuropatov.bak';
GO
